# Generated by Django 3.0 on 2024-03-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieasename', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=2000)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usage', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('price', models.CharField(default='100', max_length=50)),
                ('type', models.CharField(default='Organic Fertilizer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('FARMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.farmer_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.farmer_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=500)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='subsidy_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.product_table')),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('DISEASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Diease')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.order_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.order_table')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.product_table')),
            ],
        ),
        migrations.AddField(
            model_name='order_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.user_table'),
        ),
        migrations.CreateModel(
            name='fertbooking_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.farmer_table')),
                ('FERTILIZER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.fertilizer_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='farmer_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login_table'),
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.TextField()),
                ('date', models.DateField()),
                ('reply', models.TextField()),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.farmer_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('date', models.DateField()),
                ('reply', models.TextField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='Myapp.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='Myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.product_table')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.user_table')),
            ],
        ),
    ]
