# Generated by Django 3.0.5 on 2024-03-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_fertilizer_table_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_table',
            name='current_stock',
            field=models.CharField(default=30, max_length=50),
        ),
    ]
