# Generated by Django 3.0.5 on 2024-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_fertilizer_table_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
